-- Local development fixtures: a snapshot of the live listings from
-- https://concours.mouadlotfi.com/ (captured 2026-09-24).
--
-- Load with:   bun run db:seed
-- Clear with:  bun run db:reset
--
-- Only rows with aiRelevant = 1 are kept, matching what the home page renders.
-- Deadlines are the real snapshot values, so the pinned/urgent block will empty
-- out as those dates pass. /api/refresh does a DELETE FROM concours before
-- re-inserting scraped rows, so re-run db:seed after any refresh.

DROP TABLE IF EXISTS concours;
CREATE TABLE concours (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  wadifaUrl TEXT NOT NULL,
  sourceUrl TEXT,
  depositDeadlineIso TEXT,
  concoursDateIso TEXT,
  details TEXT, -- JSON string
  matchReason TEXT,
  aiRelevant BOOLEAN DEFAULT NULL,
  aiReason TEXT,
  classificationVersion TEXT,
  classificationHash TEXT,
  classificationSource TEXT,
  classificationModel TEXT,
  classifiedAt DATETIME,
  notifiedAt DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO concours
  (id, title, wadifaUrl, sourceUrl, depositDeadlineIso, concoursDateIso, details, matchReason, aiRelevant)
VALUES
  ('105018', 'Concours de recrutement de 2 Technicien de 3ème grade en spécialités developpement informatique systeme d informatique reseaux informatique', 'https://www.wadifa-info.com/fr/105018/', 'https://www.emploi-public.ma/fr/concours/details/bf375814-b71a-478a-bb43-2e24de7377e0', '2026-09-24T23:59:59.999Z', '2026-10-04T00:00:00.000Z', '{"Administration qui recrute":"Province de Chichaoua  - GMASSA","Spécialités requises":"developpement informatique systeme d informatique reseaux informatique","Postes":"2 postes","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"2 postes","Type de recrutement":"Recrutement régulier","Région":"Marrakech-Safi","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt papier du dossier de candidature","Date du concours":"04/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('105281', 'Concours de recrutement de 5 Technicien de 3ème grade en spécialités génie civilgros travaux et publics , développement informatique et réseaux , electricité auto', 'https://www.wadifa-info.com/fr/105281/', 'https://www.emploi-public.ma/fr/concours/details/6543acce-19a1-4b46-bd60-0bdb209fd541', '2026-09-25T23:59:59.999Z', '2026-10-11T00:00:00.000Z', '{"Administration qui recrute":"Province de Berkane  - SAIDIA","Spécialités requises":"génie civilgros travaux et publics développement informatique et réseaux electricité auto","Postes":"5 postes","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"5 postes","Type de recrutement":"Recrutement régulier","Région":"Oriental","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt papier du dossier de candidature","Date du concours":"11/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115382', 'Concours de recrutement de 5 Ingénieur d''etat 1er grade en spécialités développement informatique , statistiques , ingénierie informatique et réseaux et autres', 'https://www.wadifa-info.com/fr/115382/', 'https://www.emploi-public.ma/fr/concours/details/ea15f5d2-3657-48c0-83d4-da029a7af7ca', '2026-09-25T23:59:59.999Z', '2026-10-18T00:00:00.000Z', '{"Administration qui recrute":"Ministère de l’Inclusion économique, de la Petite entreprise, de l’Emploi et des Compétences","Spécialités requises":"développement informatique statistiques ingénierie informatique et réseaux sécurité des systèmes d''information gestion des systèmes et des plateformes informatiques","Postes":"5 postes","Diplômes":"Diplôme d Ingénieur d État","Nombre de postes":"5 postes","Type de recrutement":"Recrutement régulier","Diplômes requis":"Diplôme d Ingénieur d État","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"18/10/2026","Salaire":"10901.92 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('105214', 'Concours de recrutement de 2 Technicien de 3ème grade en spécialités génie civil et gros travaux , réseaux et développement informatique...', 'https://www.wadifa-info.com/fr/105214/', 'https://www.emploi-public.ma/fr/concours/details/180e1e5d-472d-4cea-a00e-a623beecf83c', '2026-09-28T23:59:59.999Z', '2026-10-17T00:00:00.000Z', '{"Administration qui recrute":"Province de Ouezzane  - SIDI AHMED CHERIF","Spécialités requises":"génie civil et gros travaux réseaux et développement informatique...","Postes":"2 postes","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"2 postes","Type de recrutement":"Recrutement régulier","Région":"Tanger-Tétouan-Al Hoceima","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt papier du dossier de candidature","Date du concours":"17/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115529', 'Concours de recrutement de 1 Technicien de 3ème grade en spécialités développement informatique', 'https://www.wadifa-info.com/fr/115529/', 'https://www.emploi-public.ma/fr/concours/details/0d5d0806-054d-4777-8670-ccba1ea735b2', '2026-10-03T23:59:59.999Z', '2026-10-11T00:00:00.000Z', '{"Administration qui recrute":"Université Cadi Ayyad","Spécialités requises":"développement informatique","Postes":"Un poste","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"11/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115534', 'Concours de recrutement de 1 Technicien de 3ème grade en spécialités développement informatique', 'https://www.wadifa-info.com/fr/115534/', 'https://www.emploi-public.ma/fr/concours/details/22bfb8ff-edbd-4299-90af-68f887b143ee', '2026-10-03T23:59:59.999Z', '2026-10-11T00:00:00.000Z', '{"Administration qui recrute":"Université Cadi Ayyad","Spécialités requises":"développement informatique","Postes":"Un poste","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"11/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115550', 'Concours de recrutement de 1 Administrateur 2ème grade en spécialités développement informatique', 'https://www.wadifa-info.com/fr/115550/', 'https://www.emploi-public.ma/fr/concours/details/d0952317-c3f7-4bf2-8cd4-706e2bb042f9', '2026-10-03T23:59:59.999Z', '2026-10-11T00:00:00.000Z', '{"Administration qui recrute":"Université Cadi Ayyad","Spécialités requises":"développement informatique","Postes":"Un poste","Diplômes":"Master","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Diplômes requis":"Master","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"11/10/2026","Salaire":"9505.66 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115584', 'Concours de recrutement de 1 Technicien 3ème grade à la fsa taroudant spécialité développement informatique en spécialités développement informatique', 'https://www.wadifa-info.com/fr/115584/', 'https://www.emploi-public.ma/fr/concours/details/bca396eb-03a2-4648-94e9-2f4bd888ee07', '2026-10-04T23:59:59.999Z', '2026-10-11T00:00:00.000Z', '{"Administration qui recrute":"Université Ibn Zohr - Agadir","Spécialités requises":"développement informatique","Postes":"Un poste","Diplômes":"Diplôme de Technicien","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Salaire estimé":"5,200 – 7,100 DH","Région":"Souss-Massa","Diplômes requis":"Diplôme de Technicien","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"11/10/2026"}', 'Sent directly to AI', 1),
  ('115562', 'Concours de recrutement de 1 مهندس دولة في هندسة البرمجيات والذكاء الاصطناعي وعلوم البيانات pole si sosipo ref.07/2026', 'https://www.wadifa-info.com/fr/115562/', 'https://www.emploi-public.ma/fr/concours/details/1c4103fd-834b-4fd0-bb46-a6d0b02fedc0', '2026-10-05T23:59:59.999Z', NULL, '{"Administration qui recrute":"Société des Silos Portuaires (SOSIPO)","Postes":"Un poste","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Type de dépôt":"Dépôt papier du dossier de candidature"}', 'Sent directly to AI', 1),
  ('115613', 'Concours de recrutement de 1 Technicien de 3ème grade en spécialités développement informatique', 'https://www.wadifa-info.com/fr/115613/', 'https://www.emploi-public.ma/fr/concours/details/4c9beb51-56ec-4a8c-b043-4857723f840f', '2026-10-07T23:59:59.999Z', '2026-10-18T00:00:00.000Z', '{"Administration qui recrute":"Université Cadi Ayyad","Spécialités requises":"développement informatique","Postes":"Un poste","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"18/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115643', 'Concours de recrutement de 1 Ingénieur d''etat 1er grade en spécialités génie logiciel , systèmes d''information , génie informatique et autres', 'https://www.wadifa-info.com/fr/115643/', 'https://www.emploi-public.ma/fr/concours/details/4e558e69-ac29-4153-a076-b83e3fa689ff', '2026-10-07T23:59:59.999Z', '2026-11-08T00:00:00.000Z', '{"Administration qui recrute":"Agence Marocaine de Sûreté et Sécurité Nucléaires et Radiologiques","Spécialités requises":"génie logiciel systèmes d''information génie informatique développement informatique.","Postes":"Un poste","Diplômes":"Diplôme d Ingénieur d État","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Diplômes requis":"Diplôme d Ingénieur d État","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"08/11/2026","Salaire":"10901.92 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('105017', 'Concours de recrutement de 1 Technicien de 3ème grade en spécialités developpement informatique systeme d informatique reseaux informatique', 'https://www.wadifa-info.com/fr/105017/', 'https://www.emploi-public.ma/fr/concours/details/a3367690-b2a8-4791-98cf-bfdb6af517b2', '2026-10-09T23:59:59.999Z', '2026-10-25T00:00:00.000Z', '{"Administration qui recrute":"Province de Chichaoua  - NFIFA","Spécialités requises":"developpement informatique systeme d informatique reseaux informatique","Postes":"Un poste","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"Un poste","Type de recrutement":"Recrutement régulier","Région":"Marrakech-Safi","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt papier du dossier de candidature","Date du concours":"25/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('105284', 'Concours de recrutement de 2 Technicien de 3ème grade en spécialités developpement informatique systeme d informatique reseaux informatique', 'https://www.wadifa-info.com/fr/105284/', 'https://www.emploi-public.ma/fr/concours/details/8d0939b8-ee12-4281-8507-230affe85ec8', '2026-10-09T23:59:59.999Z', '2026-10-18T00:00:00.000Z', '{"Administration qui recrute":"Province de Chichaoua  - ADASSIL","Spécialités requises":"developpement informatique systeme d informatique reseaux informatique","Postes":"2 postes","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"2 postes","Type de recrutement":"Recrutement régulier","Région":"Marrakech-Safi","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt papier du dossier de candidature","Date du concours":"18/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('125670', 'Concours de recrutement de 7 Technicien de 3ème grade en spécialités chimie , techniques de secrétariat de direction , développement informatique et autres', 'https://www.wadifa-info.com/fr/125670/', 'https://www.emploi-public.ma/fr/concours/details/d3ff3486-76fa-4edf-a028-ffce643fd5e1', '2026-10-09T23:59:59.999Z', '2026-10-18T00:00:00.000Z', '{"Administration qui recrute":"Université Sidi Mohamed Ben Abdellah -Fès-","Spécialités requises":"chimie techniques de secrétariat de direction développement informatique gestion des entreprises finance et comptabilité","Postes":"7 postes","Diplômes":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Nombre de postes":"7 postes","Type de recrutement":"Recrutement régulier","Région":"Fès-Meknès","Diplômes requis":"Diplôme de Technicien Spécialisé Diplôme Universitaire de Technologie Brevet du Technicien Supérieur","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"18/10/2026","Salaire":"5794.68 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115629', 'Concours de recrutement de 5 Technicien de 4ème grade en spécialités génie civil et gros travaux , réseaux et développement informatique... , conducteur véhicule et engins des gros travaux', 'https://www.wadifa-info.com/fr/115629/', 'https://www.emploi-public.ma/fr/concours/details/92084d9e-70c0-439e-8875-661a16fc3071', '2026-10-14T23:59:59.999Z', '2026-11-15T00:00:00.000Z', '{"Administration qui recrute":"Province de Ouezzane  - OUNNANA","Spécialités requises":"génie civil et gros travaux réseaux et développement informatique... conducteur véhicule et engins des gros travaux","Postes":"5 postes","Diplômes":"Diplôme de Technicien","Nombre de postes":"5 postes","Type de recrutement":"Recrutement régulier","Région":"Tanger-Tétouan-Al Hoceima","Diplômes requis":"Diplôme de Technicien","Type de dépôt":"Dépôt papier du dossier de candidature","Date du concours":"15/11/2026","Salaire":"5565.67 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1),
  ('115474', 'Concours de recrutement de 20 Ingénieur d''etat 1er grade en spécialités statistique et economie appliquée & démographie , sciences des données, big data et intelligence artificielle, développement informatique, réseaux et sécurité , (système d’information géographique (sig', 'https://www.wadifa-info.com/fr/115474/', 'https://www.emploi-public.ma/fr/concours/details/0bcfe0ed-c273-4358-947a-76594b2f2dde', '2026-10-15T23:59:59.999Z', '2026-10-25T00:00:00.000Z', '{"Administration qui recrute":"Haut commissariat au plan","Spécialités requises":"statistique et economie appliquée & démographie sciences des données, big data et intelligence artificielle, développement informatique, réseaux et sécurité (système d’information géographique (sig","Postes":"20 postes","Diplômes":"Diplôme d Ingénieur d État","Nombre de postes":"20 postes","Type de recrutement":"Recrutement régulier","Diplômes requis":"Diplôme d Ingénieur d État","Type de dépôt":"Dépôt électronique du dossier de candidature","Date du concours":"25/10/2026","Salaire":"10901.92 DH — Voir le salaire de ce grade →"}', 'Sent directly to AI', 1);
